//! Fast 2-D simulator for RL training.
//!
//! Generates procedural maze environments, simulates mecanum-wheel physics,
//! and produces synthetic pseudo-lidar + IMU observations at each step.
//!
//! # Design
//! - Synchronous (no async) — the RL training loop calls `step()` in a tight
//!   inner loop; async overhead would be wasted here.
//! - No external RNG dependency — uses an inline XorShift64 PRNG.
//! - Grid: 10 m × 10 m at 5 cm/cell = 200 × 200 cells.
//! - Maze: random rectangular obstacles with cleared border corridors.
//! - Pseudo-lidar: 48 rays, ±55° (110° H-FOV), 3 m max range, 1 cm step.
//! - Physics: dt = 0.1 s; 6 discrete actions matching real HAL action space.
//!
//! # Usage
//! ```ignore
//! let mut sim = FastSim::new(42, RoomKind::Random(18));
//! let obs = sim.reset();               // generate new maze, place robot
//! let obs = sim.step(Action::Forward as u8);
//! if obs.done { let obs = sim.reset(); }
//! ```

pub mod hal_impls;

use core_types::{ImuSample, LidarRay, Pose2D, PseudoLidarScan};
use tracing::debug;

// ── Constants ─────────────────────────────────────────────────────────────────

/// Grid cell side length (metres). Matches real mapping resolution.
pub const RESOLUTION_M: f32 = 0.05;

/// Arena side length in cells.
const GRID_CELLS: usize = 200;

/// Arena side length in metres (GRID_CELLS × RESOLUTION_M).
pub const ARENA_M: f32 = GRID_CELLS as f32 * RESOLUTION_M;

/// Robot collision radius (metres). Raspbot V2 is ~25 cm long.
const ROBOT_RADIUS_M: f32 = 0.15;

/// Simulation time step (seconds).
const DT_S: f32 = 0.1;

/// Number of pseudo-lidar rays.
const NUM_RAYS: usize = 48;

/// Half angle of the lidar fan (radians). 110° total.
const HALF_FOV_RAD: f32 = 55.0 * std::f32::consts::PI / 180.0;

/// Maximum lidar range (metres).
const MAX_RANGE_M: f32 = 3.0;

/// Ray-marching step (metres).
const RAY_STEP_M: f32 = 0.01;

/// Robot forward speed (m/s equivalent).
/// Calibrated 2026-03-18: measured 0.484 m/s @ 30% → 1.61 m/s @ 100% (wheels on floor)
const SPEED_M_S: f32 = 1.61;

/// Robot rotation rate (rad/s).
/// Calibrated 2026-03-18: measured 4.103 rad/s @ 30% → 13.7 rad/s @ 100% (wheels on floor)
const OMEGA_RAD_S: f32 = 13.7;

// ── Motor model ──────────────────────────────────────────────────────────────

/// Motor acceleration time constant (seconds): how fast motors ramp up.
/// Measured: real motors reach ~95% speed in ~0.5s, so tau ≈ 0.2s
const MOTOR_TAU_S: f32 = 0.2;

/// Motor braking time constant (seconds): how fast motors stop when duty → 0.
/// Yahboom H-bridge actively brakes at duty=0 (low-side short), so spin-down
/// is much faster than spin-up.  tau_brake ≈ 0.02s ≈ 1 tick to near-zero.
const BRAKE_TAU_S: f32 = 0.02;

/// Discrete acceleration filter gain: alpha = dt / (tau + dt)
const ACCEL_ALPHA: f32 = DT_S / (MOTOR_TAU_S + DT_S);

/// Discrete braking filter gain (fast): used when |target| < |current|.
const BRAKE_ALPHA: f32 = DT_S / (BRAKE_TAU_S + DT_S);

/// Episode ends after this many steps (in addition to collision).
/// At 10 Hz this is 200 seconds (~3.3 minutes) per episode.
const MAX_STEPS: u32 = 2_000;

/// Number of random rectangular obstacles per episode (default if no RoomKind is specified).
const DEFAULT_OBSTACLES: usize = 18;

// ── Room configuration ────────────────────────────────────────────────────────

/// Controls the type of environment generated by `FastSim`.
#[derive(Debug, Clone)]
pub enum RoomKind {
    /// Empty room: only border walls, no interior obstacles.
    Empty,
    /// Random rectangular obstacles. `0` is equivalent to `Empty`.
    Random(usize),
    /// Single centered square obstacle, `side_m` × `side_m`.
    /// Robot spawns at (5m, 2m) — lower third, away from the obstacle.
    SingleBox { side_m: f32 },
}

impl RoomKind {
    fn obstacle_count(&self) -> usize {
        match self {
            Self::Empty | Self::SingleBox { .. } => 0,
            Self::Random(n) => *n,
        }
    }
}

impl Default for RoomKind {
    fn default() -> Self { Self::Random(DEFAULT_OBSTACLES) }
}

// ── Action encoding ───────────────────────────────────────────────────────────

/// Six discrete actions (matches `FrontierChoice` motor encoding, not the RL
/// frontier-selection space). Used inside the sim physics engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Action {
    Forward     = 0,
    RotateLeft  = 1,
    RotateRight = 2,
    StrafeLeft  = 3,
    StrafeRight = 4,
    Stop        = 5,
}

impl Action {
    pub fn from_u8(v: u8) -> Self {
        match v {
            0 => Self::Forward,
            1 => Self::RotateLeft,
            2 => Self::RotateRight,
            3 => Self::StrafeLeft,
            4 => Self::StrafeRight,
            _ => Self::Stop,
        }
    }
}

// ── Observation ───────────────────────────────────────────────────────────────

/// Output of each `step()` / `reset()` call.
#[derive(Debug, Clone)]
pub struct SimStep {
    /// Synthetic pseudo-lidar scan (48 rays, same format as real sensor).
    pub scan: PseudoLidarScan,
    /// Synthetic IMU sample (gyro_z from rotation, zero noise).
    pub imu: ImuSample,
    /// Ground-truth robot pose (for reward computation / debugging).
    pub pose: Pose2D,
    /// True if the robot collided with a wall this step.
    pub collision: bool,
    /// True if the episode is over (collision or max steps reached).
    pub done: bool,
}

// ── FastSim ───────────────────────────────────────────────────────────────────

/// Lightweight 2-D simulator for RL training.
pub struct FastSim {
    /// Occupancy grid: `true` = wall. Row-major: index = y * GRID_CELLS + x.
    grid: Vec<bool>,
    /// Robot world-frame pose.
    robot_x: f32,
    robot_y: f32,
    robot_theta: f32,
    /// Steps taken in the current episode.
    step_count: u32,
    /// Simulated elapsed time (ms).
    t_ms: u64,
    /// Episode random seed source.
    rng: Rng,
    /// Angular velocity from the last step (for IMU).
    last_omega: f32,
    /// Room configuration used when (re)generating the maze.
    room_kind: RoomKind,
    /// Current velocity state (m/s) for acceleration model.
    current_vx: f32,
    current_vy: f32,
    current_omega: f32,
}

impl FastSim {
    /// Returns the ground-truth wall grid: flat `bool` slice, row-major `y * GRID_CELLS + x`.
    pub fn wall_grid(&self) -> &[bool] { &self.grid }

    /// Create a new simulator with the given random seed and room configuration.
    pub fn new(seed: u64, room_kind: RoomKind) -> Self {
        let mut sim = Self {
            grid: vec![false; GRID_CELLS * GRID_CELLS],
            robot_x: ARENA_M * 0.5,
            robot_y: ARENA_M * 0.5,
            robot_theta: 0.0,
            step_count: 0,
            t_ms: 0,
            rng: Rng::new(seed),
            last_omega: 0.0,
            room_kind,
            current_vx: 0.0,
            current_vy: 0.0,
            current_omega: 0.0,
        };
        sim.generate_maze();
        sim
    }

    /// Reset the simulator: generate a new maze and return the initial observation.
    pub fn reset(&mut self) -> SimStep {
        self.step_count = 0;
        self.t_ms = 0;
        self.last_omega = 0.0;
        self.current_vx = 0.0;
        self.current_vy = 0.0;
        self.current_omega = 0.0;
        self.generate_maze();
        self.make_step(false)
    }

    /// Reposition the robot to the centre of the **current** maze without
    /// regenerating walls.  Used in single-episode explore mode so the
    /// occupancy map survives a collision respawn.
    pub fn respawn(&mut self) -> SimStep {
        self.step_count = 0;
        self.last_omega = 0.0;
        self.current_vx = 0.0;
        self.current_vy = 0.0;
        self.current_omega = 0.0;
        let start_x = ARENA_M * 0.5;
        let start_y = ARENA_M * 0.5;
        let (rx, ry) = self.nearest_free(start_x, start_y);
        self.robot_x = rx;
        self.robot_y = ry;
        self.robot_theta = self.rng.next_f32() * 2.0 * std::f32::consts::PI;
        self.make_step(false)
    }

    /// Advance the simulation by one time step.
    /// `pan_deg` shifts the camera's field of view: >0 = looking right, <0 = left.
    /// Use `step()` for pan=0 (backward-compatible).
    pub fn step_with_pan(&mut self, action: u8, pan_deg: f32) -> SimStep {
        let act = Action::from_u8(action);
        let (target_vx, target_vy, target_omega) = action_to_velocity(act);

        // Apply first-order acceleration filter with separate spin-up / brake alphas.
        // When |target| < |current| the H-bridge is actively braking — use BRAKE_ALPHA
        // (fast) so the coast matches real hardware.  Spin-up uses ACCEL_ALPHA (slow).
        let ax = if target_vx.abs()    >= self.current_vx.abs()    { ACCEL_ALPHA } else { BRAKE_ALPHA };
        let ay = if target_vy.abs()    >= self.current_vy.abs()    { ACCEL_ALPHA } else { BRAKE_ALPHA };
        let aw = if target_omega.abs() >= self.current_omega.abs() { ACCEL_ALPHA } else { BRAKE_ALPHA };
        self.current_vx    = (1.0 - ax) * self.current_vx    + ax * target_vx;
        self.current_vy    = (1.0 - ay) * self.current_vy    + ay * target_vy;
        self.current_omega = (1.0 - aw) * self.current_omega + aw * target_omega;

        // Compute proposed new pose using current (accelerated) velocity.
        let cos_t = self.robot_theta.cos();
        let sin_t = self.robot_theta.sin();
        let try_x = self.robot_x + (self.current_vx * cos_t - self.current_vy * sin_t) * DT_S;
        let try_y = self.robot_y + (self.current_vx * sin_t + self.current_vy * cos_t) * DT_S;
        let new_theta = wrap_angle(self.robot_theta + self.current_omega * DT_S);

        // Collision check on proposed position.
        let collision = !self.robot_clear(try_x, try_y);
        if !collision {
            self.robot_x = try_x;
            self.robot_y = try_y;
        }
        self.robot_theta = new_theta;
        self.last_omega = self.current_omega;
        self.step_count += 1;
        self.t_ms += (DT_S * 1000.0) as u64;

        let done = collision || self.step_count >= MAX_STEPS;
        self.make_step_pan(collision, pan_deg)
            .with_done(done)
    }

    /// Advance the simulation by one time step with the camera pointing forward.
    pub fn step(&mut self, action: u8) -> SimStep {
        self.step_with_pan(action, 0.0)
    }

    /// Advance the simulation using continuous proportional velocity targets
    /// (m/s for translation, rad/s for rotation, in sim velocity units).
    ///
    /// Unlike `step_with_pan` this does not snap to a discrete action, so
    /// blended forward+rotation commands (e.g. from the pure-pursuit controller)
    /// are executed faithfully rather than losing the rotation component due to
    /// sign truncation in the MotorCommand integer encoding.
    pub fn step_continuous(&mut self, target_vx: f32, target_vy: f32, target_omega: f32, pan_deg: f32) -> SimStep {
        let ax = if target_vx.abs()    >= self.current_vx.abs()    { ACCEL_ALPHA } else { BRAKE_ALPHA };
        let ay = if target_vy.abs()    >= self.current_vy.abs()    { ACCEL_ALPHA } else { BRAKE_ALPHA };
        let aw = if target_omega.abs() >= self.current_omega.abs() { ACCEL_ALPHA } else { BRAKE_ALPHA };
        self.current_vx    = (1.0 - ax) * self.current_vx    + ax * target_vx;
        self.current_vy    = (1.0 - ay) * self.current_vy    + ay * target_vy;
        self.current_omega = (1.0 - aw) * self.current_omega + aw * target_omega;

        let cos_t = self.robot_theta.cos();
        let sin_t = self.robot_theta.sin();
        let try_x = self.robot_x + (self.current_vx * cos_t - self.current_vy * sin_t) * DT_S;
        let try_y = self.robot_y + (self.current_vx * sin_t + self.current_vy * cos_t) * DT_S;
        let new_theta = wrap_angle(self.robot_theta + self.current_omega * DT_S);

        let collision = !self.robot_clear(try_x, try_y);
        if !collision {
            self.robot_x = try_x;
            self.robot_y = try_y;
        }
        self.robot_theta = new_theta;
        self.last_omega = self.current_omega;
        self.step_count += 1;
        self.t_ms += (DT_S * 1000.0) as u64;

        let done = collision || self.step_count >= MAX_STEPS;
        self.make_step_pan(collision, pan_deg)
            .with_done(done)
    }

    /// Return the centered (pan=0) scan at the current robot position without
    /// advancing physics.  Used by navigation heuristics that must see the full
    /// forward corridor regardless of where the visual gimbal is pointing.
    pub fn nav_scan(&self) -> PseudoLidarScan {
        self.cast_lidar_pan(0.0)
    }

    /// Cast a single ray from the robot's current position at the given world-frame angle.
    /// Used by `SimCamera` to render first-person perspective frames.
    pub fn cast_single_ray(&self, world_angle_rad: f32) -> f32 {
        self.cast_ray(self.robot_x, self.robot_y, world_angle_rad)
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    fn make_step_pan(&self, collision: bool, pan_deg: f32) -> SimStep {
        SimStep {
            scan:      self.cast_lidar_pan(pan_deg),
            imu:       self.synthetic_imu(),
            pose:      self.pose(),
            collision,
            done: false, // caller sets this
        }
    }

    fn make_step(&self, collision: bool) -> SimStep {
        self.make_step_pan(collision, 0.0)
    }

    pub fn pose(&self) -> Pose2D {
        Pose2D {
            t_ms: self.t_ms,
            x_m: self.robot_x,
            y_m: self.robot_y,
            theta_rad: self.robot_theta,
            confidence: 1.0, // ground truth
        }
    }

    fn synthetic_imu(&self) -> ImuSample {
        ImuSample {
            t_ms: self.t_ms,
            gyro_x: 0.0,
            gyro_y: 0.0,
            gyro_z: self.last_omega,
            accel_x: 0.0,
            accel_y: 0.0,
            accel_z: 9.81,
        }
    }

    // ── Raycasting ────────────────────────────────────────────────────────────

    /// Cast a pseudo-lidar scan with the camera centred at `pan_deg` offset.
    ///
    /// `pan_deg` > 0 = camera looking right (hardware convention: pan_deg = +90 → raw=0 → right).
    /// In the robot's angle frame (positive = CCW = left), right = negative, so the fan centre
    /// shifts by `-pan_deg * π/180`.  Ray `angle_rad` values are always in robot frame.
    fn cast_lidar_pan(&self, pan_deg: f32) -> PseudoLidarScan {
        let pan_rad = -pan_deg * std::f32::consts::PI / 180.0;
        let mut rays = Vec::with_capacity(NUM_RAYS);
        for i in 0..NUM_RAYS {
            let frac = i as f32 / (NUM_RAYS - 1) as f32; // 0..1
            let local_angle = pan_rad + (-HALF_FOV_RAD + frac * 2.0 * HALF_FOV_RAD);
            let world_angle = self.robot_theta + local_angle;
            let range = self.cast_ray(self.robot_x, self.robot_y, world_angle);
            rays.push(LidarRay {
                angle_rad:  local_angle,
                range_m:    range,
                confidence: 1.0,
            });
        }
        PseudoLidarScan { t_ms: self.t_ms, rays }
    }


    /// Cast a VL53L5CX ToF sensor scan: 8 column-averaged rays across ±19.69°,
    /// panned to `pan_deg`.  Same pan convention as `cast_lidar_pan`.
    ///
    /// Column centres (robot frame): `(col − 3.5) × 5.625°` for col in 0..8.
    /// Angles: −19.69°, −14.06°, −8.44°, −2.81°, +2.81°, +8.44°, +14.06°, +19.69°.
    pub fn cast_tof(&self, pan_deg: f32) -> PseudoLidarScan {
        const TOF_COLS: usize = 8;
        const COL_STEP_RAD: f32 = 5.625 * std::f32::consts::PI / 180.0;
        let pan_rad = -pan_deg * std::f32::consts::PI / 180.0;
        let mut rays = Vec::with_capacity(TOF_COLS);
        for col in 0..TOF_COLS {
            let local_angle = pan_rad + (col as f32 - 3.5) * COL_STEP_RAD;
            let world_angle = self.robot_theta + local_angle;
            let range = self.cast_ray(self.robot_x, self.robot_y, world_angle);
            rays.push(LidarRay {
                angle_rad:  local_angle,
                range_m:    range,
                confidence: 1.0,
            });
        }
        PseudoLidarScan { t_ms: self.t_ms, rays }
    }

    fn cast_ray(&self, ox: f32, oy: f32, angle: f32) -> f32 {
        let dx = angle.cos() * RAY_STEP_M;
        let dy = angle.sin() * RAY_STEP_M;
        let mut rx = ox;
        let mut ry = oy;
        let mut dist = 0.0f32;
        while dist < MAX_RANGE_M {
            rx += dx;
            ry += dy;
            dist += RAY_STEP_M;
            let cx = (rx / RESOLUTION_M) as i32;
            let cy = (ry / RESOLUTION_M) as i32;
            if cx < 0 || cy < 0
                || cx >= GRID_CELLS as i32
                || cy >= GRID_CELLS as i32
            {
                // Step landed outside the grid.  Back up one step so the
                // endpoint stays within the valid boundary — prevents the
                // mapper from creating cells at negative or out-of-range
                // indices, which form spurious frontier clusters outside
                // the arena walls.
                return (dist - RAY_STEP_M).max(0.0);
            }
            if self.wall(cx as usize, cy as usize) {
                return dist;
            }
        }
        MAX_RANGE_M
    }

    // ── Collision detection ───────────────────────────────────────────────────

    fn robot_clear(&self, x: f32, y: f32) -> bool {
        let r = ROBOT_RADIUS_M;
        let cell_r = (r / RESOLUTION_M).ceil() as i32 + 1;
        let cx = (x / RESOLUTION_M) as i32;
        let cy = (y / RESOLUTION_M) as i32;
        for dx in -cell_r..=cell_r {
            for dy in -cell_r..=cell_r {
                let nx = cx + dx;
                let ny = cy + dy;
                if nx < 0 || ny < 0 || nx >= GRID_CELLS as i32 || ny >= GRID_CELLS as i32 {
                    return false;
                }
                let dist = (dx as f32 * RESOLUTION_M).hypot(dy as f32 * RESOLUTION_M);
                if dist <= r && self.wall(nx as usize, ny as usize) {
                    return false;
                }
            }
        }
        true
    }

    // ── Grid accessors ────────────────────────────────────────────────────────

    fn wall(&self, x: usize, y: usize) -> bool {
        self.grid[y * GRID_CELLS + x]
    }

    fn set_wall(&mut self, x: usize, y: usize, v: bool) {
        self.grid[y * GRID_CELLS + x] = v;
    }

    // ── Maze generation ───────────────────────────────────────────────────────

    fn generate_maze(&mut self) {
        // Clear all walls.
        self.grid.fill(false);

        // Border walls (2 cells thick for safety margin).
        let g = GRID_CELLS;
        for i in 0..g {
            for t in 0..3 {
                self.set_wall(i, t, true);
                self.set_wall(i, g - 1 - t, true);
                self.set_wall(t, i, true);
                self.set_wall(g - 1 - t, i, true);
            }
        }

        // Interior obstacles.
        match &self.room_kind.clone() {
            RoomKind::SingleBox { side_m } => {
                // One square obstacle centered at (5m, 5m).
                let half_cells = ((side_m / 2.0) / RESOLUTION_M) as usize;
                let center = GRID_CELLS / 2; // 100
                let x0 = center.saturating_sub(half_cells);
                let x1 = (center + half_cells).min(g - 1);
                let y0 = center.saturating_sub(half_cells);
                let y1 = (center + half_cells).min(g - 1);
                for ry in y0..=y1 {
                    for rx in x0..=x1 {
                        self.set_wall(rx, ry, true);
                    }
                }
            }
            _ => {
                // Random rectangular obstacles.
                let n_obstacles = self.room_kind.obstacle_count();
                let min_cells = 4usize;  // 20 cm minimum obstacle dimension
                let max_cells = 30usize; // 150 cm maximum
                for _ in 0..n_obstacles {
                    let w = min_cells + self.rng.next_usize(max_cells - min_cells + 1);
                    let h = min_cells + self.rng.next_usize(max_cells - min_cells + 1);
                    // Keep away from borders.
                    let x0 = 4 + self.rng.next_usize(g - w - 8);
                    let y0 = 4 + self.rng.next_usize(g - h - 8);
                    for ry in y0..(y0 + h).min(g) {
                        for rx in x0..(x0 + w).min(g) {
                            self.set_wall(rx, ry, true);
                        }
                    }
                }
            }
        }

        // Place robot: SingleBox starts in the lower third, others near centre.
        let (start_x, start_y) = if matches!(self.room_kind, RoomKind::SingleBox { .. }) {
            (ARENA_M * 0.5, ARENA_M * 0.2)  // (5m, 2m) — lower third
        } else {
            (ARENA_M * 0.5, ARENA_M * 0.5)
        };
        let (rx, ry) = self.nearest_free(start_x, start_y);
        self.robot_x = rx;
        self.robot_y = ry;
        self.robot_theta = self.rng.next_f32() * 2.0 * std::f32::consts::PI;

        debug!(
            obstacles = self.room_kind.obstacle_count(),
            robot_x   = self.robot_x,
            robot_y   = self.robot_y,
            "Maze generated"
        );
    }

    fn nearest_free(&self, world_x: f32, world_y: f32) -> (f32, f32) {
        let cx0 = (world_x / RESOLUTION_M) as i32;
        let cy0 = (world_y / RESOLUTION_M) as i32;
        // Spiral outward.
        for radius in 0..(GRID_CELLS as i32 / 2) {
            for dx in -radius..=radius {
                for dy in -radius..=radius {
                    if dx.abs().max(dy.abs()) != radius { continue; }
                    let nx = cx0 + dx;
                    let ny = cy0 + dy;
                    if nx < 0 || ny < 0 || nx >= GRID_CELLS as i32 || ny >= GRID_CELLS as i32 {
                        continue;
                    }
                    let wx = nx as f32 * RESOLUTION_M + RESOLUTION_M * 0.5;
                    let wy = ny as f32 * RESOLUTION_M + RESOLUTION_M * 0.5;
                    if self.robot_clear(wx, wy) {
                        return (wx, wy);
                    }
                }
            }
        }
        // Fallback (should not happen in a well-formed maze).
        (world_x, world_y)
    }
}

// ── SimStep helpers ───────────────────────────────────────────────────────────

impl SimStep {
    fn with_done(mut self, done: bool) -> Self {
        self.done = done;
        self
    }
}

// ── Free functions ────────────────────────────────────────────────────────────

/// Map a discrete action to `(vx, vy, omega)` in robot frame.
/// Decode a `MotorCommand` back to continuous target velocities in sim space
/// using the inverse of the standard mecanum kinematics applied in `cmdvel_to_motor`.
///
/// `cmdvel_to_motor` maps:  fl = vx_n + vy_n − ω_n,  fr = vx_n − vy_n + ω_n,
///                          rl = vx_n − vy_n − ω_n,  rr = vx_n + vy_n + ω_n
/// Inverse:  vx_n = (fl+fr+rl+rr)/4,  vy_n = (fl+rr−fr−rl)/4,  ω_n = (fr+rr−fl−rl)/4
/// Velocities are then scaled to sim space by SPEED_M_S / OMEGA_RAD_S.
///
/// Used by the sim tick task so that blended forward+rotation CmdVels produced
/// by the pure-pursuit controller execute proportionally rather than snapping to
/// one of the six discrete actions (which caused the rotation component to be
/// lost when the integer FR duty cycle truncated to zero).
pub fn motor_cmd_to_vel(fl: i8, fr: i8, rl: i8, rr: i8, max_duty: i8) -> (f32, f32, f32) {
    let d = max_duty as f32;
    let fl = fl as f32 / d;
    let fr = fr as f32 / d;
    let rl = rl as f32 / d;
    let rr = rr as f32 / d;
    let vx_n    = (fl + fr + rl + rr) * 0.25;
    let vy_n    = (fl + rr - fr - rl) * 0.25;
    let omega_n = (fr + rr - fl - rl) * 0.25;
    // SPEED_M_S / OMEGA_RAD_S are at 100% duty; scale by actual duty fraction
    // so sim velocities reflect the real motor cap (max_duty=35 → 35% of peak).
    let duty_scale = d / 100.0;
    (vx_n * SPEED_M_S * duty_scale, vy_n * SPEED_M_S * duty_scale, omega_n * OMEGA_RAD_S * duty_scale)
}

fn action_to_velocity(action: Action) -> (f32, f32, f32) {
    match action {
        Action::Forward     => (SPEED_M_S,  0.0,       0.0),
        Action::RotateLeft  => (0.0,        0.0,       OMEGA_RAD_S),
        Action::RotateRight => (0.0,        0.0,      -OMEGA_RAD_S),
        Action::StrafeLeft  => (0.0,        SPEED_M_S, 0.0),
        Action::StrafeRight => (0.0,       -SPEED_M_S, 0.0),
        Action::Stop        => (0.0,        0.0,       0.0),
    }
}

fn wrap_angle(a: f32) -> f32 {
    use std::f32::consts::PI;
    let mut a = a % (2.0 * PI);
    if a >  PI { a -= 2.0 * PI; }
    if a < -PI { a += 2.0 * PI; }
    a
}

// ── XorShift64 PRNG ───────────────────────────────────────────────────────────

struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(if seed == 0 { 0xdeadbeef_cafebabe } else { seed })
    }

    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }

    fn next_usize(&mut self, n: usize) -> usize {
        (self.next() as usize) % n
    }

    fn next_f32(&mut self) -> f32 {
        (self.next() >> 11) as f32 / (1u64 << 53) as f32
    }
}
